# Generated by Django 5.0.4 on 2025-10-20 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('password_hash', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('height', models.DecimalField(decimal_places=0, max_digits=5)),
                ('date_registered', models.DateField()),
                ('date_unregistered', models.DateField()),
                ('registered', models.BooleanField()),
                ('fitness_goal', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=50)),
            ],
        ),
    ]
