# Generated by Django 5.0.4 on 2025-10-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutware_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
                ('equipment', models.CharField(max_length=50)),
                ('difficulty', models.IntegerField()),
                ('description', models.TextField()),
                ('demo_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='user_info',
        ),
    ]
