# Generated by Django 5.0.4 on 2025-10-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutware_app', '0002_exercise_rename_user_user_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_info',
            options={'managed': False},
        ),
    ]
