# Generated by Django 5.0.4 on 2025-10-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutware_app', '0003_alter_user_info_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='user_info',
            table='user_info',
        ),
    ]
