# Generated by Django 5.0.4 on 2025-10-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutware_app', '0004_alter_exercise_options_alter_user_info_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercise',
            table='exercise',
        ),
    ]
